const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const js=html.match(/<script>([\s\S]*?)<\/script>\s*<\/body>/)[1];
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
const elements=new Map();
function element(id){if(!elements.has(id)){
 const values=new Set(id==='setup' || id==='rosterMessage'?[]:['hidden']);
 const listeners={};
 elements.set(id,{id,value:'',textContent:'',innerHTML:'',style:{},disabled:false,files:[],attributes:{},classList:{contains:x=>values.has(x),add:x=>values.add(x),remove:x=>values.delete(x),toggle:(x,force)=>{if(force===undefined? !values.has(x):force)values.add(x);else values.delete(x)}},addEventListener(type,fn){listeners[type]=fn},dispatchEvent(event){listeners[event.type]?.(event)},setAttribute(name,value){this.attributes[name]=value},focus(){this.focused=true},closest(){return null},click(){this.onclick?.()},cloneNode(){return {classList:{remove(){}},querySelectorAll:()=>[],outerHTML:'<section id=\"report\"><div>توقيع المعلم</div></section>'}}});
}return elements.get(id)}
ids.forEach(element);element('level').value='fatha';element('wordSession').value='full';
const storage=new Map(),localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
let now=1000000,printed='',printCalls=0,pdfCalls=0;
const previewElements=new Map();
const FakeDate=class extends Date {constructor(...args){super(...(args.length?args:[now]))} static now(){return now}};
const levelButtons=[...html.matchAll(/data-select-level="([^"]+)"/g)].map((match,index)=>{const button=element('level-card-'+index);button.dataset={selectLevel:match[1]};return button});
const scoreButtons=['✓','✕','↻'].map((score,index)=>{const button=element('score-'+index);button.dataset={score};return button});
const document={fonts:{ready:Promise.resolve()},getElementById:element,querySelector:selector=>({textContent:html.match(/<style>([\s\S]*?)<\/style>/)[1]}),querySelectorAll:selector=>{
 if(selector==='[data-history-class]'||selector==='[data-history-test]') {
  const attribute=selector.slice(1,-1),key=attribute==='data-history-class'?'historyClass':'historyTest';
  return [...element('historyList').innerHTML.matchAll(new RegExp(attribute+'="([^"\\n]+)"','g'))].map((m,i)=>{const button=element(attribute+'-'+i);button.dataset={[key]:m[1]};return button});
 }
 return selector==='[data-select-level]'?levelButtons:selector==='[data-score]'?scoreButtons:[]},addEventListener(){},createElement:()=>({click(){},set href(v){},set download(v){}})};
const window={printActions:{openPreview:async html=>{printed=html;return {opened:true}}},confirm:()=>true,alert:()=>{},setInterval:()=>1,clearInterval:()=>{},setTimeout:()=>1,open:()=>({document:{open(){},write(x){printed=x},close(){},getElementById:id=>{if(!previewElements.has(id))previewElements.set(id,{onclick:null,textContent:''});return previewElements.get(id)}},printActions:{print:async()=>{printCalls++;return {success:true}},savePdf:async()=>{pdfCalls++;return {saved:true}}}})};
const ctx=vm.createContext({document,window,alert:window.alert,localStorage,Date:FakeDate,console,Intl,Event,crypto:require('node:crypto').webcrypto,Blob,Response,TextDecoder,DecompressionStream,Uint8Array,DataView,globalThis:null});ctx.globalThis=ctx;
storage.set('arabic-letter-assessment.teacher-name','معلم النسخة السابقة');
storage.set('arabic-letter-assessment.principal-name','مدير النسخة السابقة');
storage.set('lughaty-oral-diagnostic.principal-name','مدير النسخة الحالية');
vm.runInContext(js,ctx);
assert.equal(storage.get('lughaty-oral-diagnostic.teacher-name'),'معلم النسخة السابقة');
assert.equal(storage.get('lughaty-oral-diagnostic.principal-name'),'مدير النسخة الحالية');
assert.equal(storage.get('arabic-letter-assessment.teacher-name'),'معلم النسخة السابقة');
const run=x=>vm.runInContext(x,ctx);
assert.equal(run('FATHA_WORDS.length'),12);
assert.equal(run('FATHA_WORDS.every(w=>!/[ًٌٍُِْ]/.test(w))'),true);
assert.equal(run('VOCALIZED_WORDS.every(w=>[...w.replace(/[\\u064B-\\u065F]/g,"")].length>=3 && [...w.replace(/[\\u064B-\\u065F]/g,"")].length<=4)'),true);
assert.equal(levelButtons.length,7);levelButtons.find(x=>x.dataset.selectLevel==='fatha').click();
assert.equal(element('level').value,'fatha');assert.equal(levelButtons.find(x=>x.dataset.selectLevel==='fatha').attributes['aria-pressed'],'true');
element('student').value='ريم الحربي';element('start').click();
assert.ok(element('testLevel').textContent.includes('كلمات'));
assert.equal(run('elapsedSeconds()'),0);assert.equal(run('assessmentStartedAt'),0);
scoreButtons[0].click();now+=61000;
assert.equal(run('elapsedSeconds()'),61);
run('previousItem()');assert.equal(run('res[0].score'),'✓');
run('nextItem()');assert.equal(run('res[0].score'),'✓');
assert.equal(JSON.parse(storage.get('lughaty-oral-diagnostic.draft')).res.filter(Boolean).length,1);
run('goHome()');run('resumeDraft()');assert.equal(run('elapsedSeconds()'),61);
assert.ok(element('testLevel').textContent.includes('كلمات'));
run("mark('✕')");assert.equal(run('res.filter(Boolean).length'),2);
run('completeAssessment()');
const record=JSON.parse(storage.get('lughaty-oral-diagnostic.records')).records[0];
assert.equal(record.summary.total,2);assert.equal(record.summary.correct,1);assert.equal(record.summary.incorrect,1);assert.equal(record.durationSeconds,61);
assert.equal(storage.has('lughaty-oral-diagnostic.draft'),false);
assert.ok(element('signatures').innerHTML.includes('مدير المدرسة'));
for(const [level,total] of [['one',28],['two',28],['three',56],['fatha',12],['vocalized',12],['four',30],['five',22]]){
  element('level').value=level;assert.equal(run('build().length'),total,level);
}
element('printFormat').value='detailed';run('renderDetails(activeRecord)');
assert.ok(element('details').innerHTML.includes('detail-table'));
element('printFormat').value='brief';run('renderDetails(activeRecord)');
assert.ok(!element('details').innerHTML.includes('detail-table'));
element('navHistory').click();assert.equal(element('history').classList.contains('hidden'),false);
assert.ok(element('historyList').innerHTML.includes('نتائج دون صف'));run('historyAll=true;renderHistoryRows()');assert.ok(element('historyList').innerHTML.includes('ريم الحربي'));assert.ok(element('historyStats').innerHTML.includes('إجمالي المحاولات'));
element('historySearch').value='لا يوجد';run('renderHistoryRows()');assert.ok(element('historyList').innerHTML.includes('لا توجد نتائج'));
element('historySearch').value='';run('renderHistoryRows()');assert.ok(element('historyList').innerHTML.includes('ريم الحربي'));
element('navSettings').click();assert.equal(element('schoolPage').classList.contains('hidden'),false);
element('schoolName').value='مدرسة الريان الابتدائية';element('saveSchool').click();
assert.equal(JSON.parse(storage.get('lughaty-oral-diagnostic.school-info')).name,'مدرسة الريان الابتدائية');
run('renderReport(activeRecord)');assert.ok(element('summary').innerHTML.includes('مدرسة الريان الابتدائية'));
run("runPrintWithFreshLayout(null,'report')");assert.ok(printed.includes('@page { size: A4'));assert.ok(printed.includes('توقيع'));
assert.ok(printed.includes('report-school') && printed.includes('#schoolPage'));
assert.ok(printed.includes('.side-nav,.no-print') && printed.includes('background:#fff!important'));
const rows=run("parseReviewRows('ريم الحربي\\tمحمد الحربي\\nعمر العتيبي')");assert.equal(rows.length,2);assert.equal(rows[0].guardianName,'محمد الحربي');
element('rosterName').value='الثاني أ';ctx.rosterRows=rows;ctx.rosterFile={name:'students.xlsx'};
run('saveImportedRoster(rosterFile,rosterRows)');run('saveImportedRoster(rosterFile,rosterRows)');
assert.equal(JSON.parse(storage.get('lughaty-oral-diagnostic.roster')).rosters.length,1);
const store=JSON.parse(storage.get('lughaty-oral-diagnostic.records'));
store.records.unshift({...record,id:'second-attempt',summary:{...record.summary,percentage:75},completedAt:new Date(now+60000).toISOString()});
storage.set('lughaty-oral-diagnostic.records',JSON.stringify(store));
ctx.profileRecord=record;run('showStudentProfile(profileRecord)');
assert.ok(element('profileContent').innerHTML.includes('أول محاولة 50%'));
assert.ok(element('profileContent').innerHTML.includes('آخر محاولة 75%'));
console.log('PASS: source word constraints, timer, navigation, draft resume, partial report, signatures, print preview, import association');

(async()=>{const previewScript=printed.match(/<script>([\s\S]*?)<\/script>/)[1];
const previewContext=vm.createContext({document:{fonts:{ready:Promise.resolve()},getElementById:id=>{if(!previewElements.has(id))previewElements.set(id,{disabled:false,textContent:''});return previewElements.get(id)}},window:{printActions:{print:async()=>{printCalls++;return {success:true}},savePdf:async()=>{pdfCalls++;return {saved:true}}}},requestAnimationFrame:fn=>fn()});
vm.runInContext(previewScript,previewContext);
await previewElements.get('doPrint').onclick();await previewElements.get('savePdf').onclick();assert.equal(printCalls,1);assert.equal(pdfCalls,1);assert.ok(previewElements.get('printStatus').textContent.includes('PDF'));console.log('PASS: self-contained print/PDF preview controls');for(const type of ['docx','xlsx']){const bytes=fs.readFileSync(__dirname+'/tests/roster-test.'+type);const file={arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteLength+bytes.byteOffset)};ctx.testFile=file;const students=await run(type==='docx'?'importDocxRoster(testFile)':'importXlsxRoster(testFile)');assert.equal(students.length,2,type);assert.equal(students[0].name,'ريم الحربي');assert.equal(students[0].guardianName,'محمد الحربي');}for(const type of ['docx','xlsx']) {
 const bytes=fs.readFileSync(__dirname+'/tests/roster-columns.'+type);
 ctx.testFile={arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};
 const students=await run(type==='docx'?'importDocxRoster(testFile)':'importXlsxRoster(testFile)');
 assert.equal(students.length,8,type+' complete count');
 assert.equal(students.filter(x=>x.name==='ريم الحربي').length,2);
 assert.ok(students.some(x=>x.name==='عبدالمجيد العامري'));
 assert.ok(students.some(x=>x.name.split(' ').length===7));
 ctx.multiRows=students;ctx.rosterFile={name:'multiple.'+type};element('rosterName').value='متعدد '+type;
 run('saveImportedRoster(rosterFile,multiRows)');const prior=JSON.parse(run('JSON.stringify(getRoster())'));
 assert.equal(prior.students.length,8);assert.notEqual(prior.students[3].id,prior.students[4].id);
 run('saveImportedRoster(rosterFile,multiRows)');assert.deepEqual(JSON.parse(run('JSON.stringify(getRoster().students.map(s=>s.id))')),prior.students.map(s=>s.id));
}
assert.equal(run("isStudentName('عبدالمجيد العامري')"),true);
assert.equal(run("isStudentName('اسم الطالب')"),false);
assert.equal(run("isStudentName('مدرسة الريان الابتدائية')"),false);
assert.equal(run("parseReviewRows('عبدالمجيد العامري\\nعبدالرحمن محمد عبدالله أحمد صالح علي الحربي').length"),2);
const item=(str,x,y,width=80)=>({str,width,transform:[1,0,0,1,x,y]});
ctx.pdfItems=[item('م',560,700,15),item('اسم الطالب',400,700),item('ولي الأمر',200,700),item('1',560,650,15),item('عبدالمجيد العامري',370,650,110),item('أحمد العامري',180,650,100),item('2',560,600,15),item('ريم الحربي',400,600),item('محمد الحربي',200,600)];
assert.deepEqual(JSON.parse(run('JSON.stringify(pdfRosterPage(pdfItems).names)')),['عبدالمجيد العامري','ريم الحربي']);
const layout=run('pdfRosterPage(pdfItems).layout');ctx.pdfLayout=layout;ctx.pdfItems=[item('3',560,600,15),item('نورة العتيبي',400,600),item('عبدالله العتيبي',200,600)];
assert.deepEqual(JSON.parse(run('JSON.stringify(pdfRosterPage(pdfItems,pdfLayout).names)')),['نورة العتيبي']);
// Old/manual attempts join a unique student in the same roster, not another class.
storage.delete('lughaty-oral-diagnostic.roster');element('rosterName').value='الثاني أ';ctx.rosterFile={name:'unique.xlsx'};ctx.multiRows=[{name:'عبدالمجيد العامري',guardianName:''}];run('saveImportedRoster(rosterFile,multiRows)');
const roster=JSON.parse(run('JSON.stringify(getRoster())'));const base={...record,studentName:'عبدالمجيد العامري',rosterId:roster.id,rosterName:roster.name};
ctx.reference={...base,studentId:roster.students[0].id};ctx.legacy={...base,studentId:'old-id'};
assert.equal(run('sameStudent(legacy,reference)'),true);
ctx.manual={...base,rosterId:null,studentId:'manual-id'};assert.equal(run('sameStudent(manual,reference)'),true);
ctx.other={...base,rosterId:'another-class',studentId:'different'};assert.equal(run('sameStudent(other,reference)'),false);
ctx.historyStore={version:2,records:[{...base,id:'old',studentId:'old-id',completedAt:'2026-10-01T10:00:00Z',summary:{...record.summary,percentage:25}},{...base,id:'new',studentId:'old-id',completedAt:'2026-10-02T10:00:00Z',summary:{...record.summary,percentage:75}}]};run('saveStore(historyStore)');
assert.equal(run('classRows()[0][2]'),'75%');assert.equal(run('allRows()[0].length'),4);assert.equal(run('classRows()[0].length'),4);
run('renderAllReport()');assert.ok(!element('allReportContent').innerHTML.includes('ولي الأمر'));assert.ok(!element('allReportContent').innerHTML.includes('<th>المدير'));
run('showStudentProfile(reference)');assert.ok(element('profileMeta').textContent.includes('2 تقييمات'));
element('historySearch').value='بحث قديم';run('showHistory(true)');run('historyAll=true;renderHistoryRows()');assert.equal(element('historySearch').value,'');assert.ok(element('historyList').innerHTML.includes('عبدالمجيد العامري'));
assert.ok(!ids.includes('schoolCity')&&!ids.includes('schoolPhone'));
assert.ok(printed.includes('.hidden { display:none!important; }'));
// Print and PDF failures must be visible, and controls must become usable again.
vm.runInContext("window.printActions.print=async()=>({success:false,reason:'لا توجد طابعة'})",previewContext);
await previewElements.get('doPrint').onclick();assert.ok(previewElements.get('printStatus').textContent.includes('لا توجد طابعة'));assert.equal(previewElements.get('doPrint').disabled,false);
vm.runInContext("window.printActions.savePdf=async()=>{throw new Error('فشل الحفظ')}",previewContext);
await previewElements.get('savePdf').onclick();assert.ok(previewElements.get('printStatus').textContent.includes('فشل الحفظ'));assert.equal(previewElements.get('savePdf').disabled,false);
console.log('PASS: multi-column/multi-sheet/full Arabic names/duplicates, PDF geometry, legacy student linkage, latest class results, visible print failures');

// Folders, batch continuity, duplicate class names, and scoped reporting.
storage.clear();now=Date.parse('2026-10-04T18:00:00Z');run('historyClassKey=null;historyTestKey=null;historyAll=false;currentTestSession=null;activeRecord=null;goHome()');
ctx.classFile={name:'first.xlsx'};ctx.classStudents=[{name:'ريم الحربي'},{name:'عمر العتيبي'},{name:'نورة الزهراني'}];
element('rosterName').value='الصف الأول — أ';run('saveImportedRoster(classFile,classStudents)');
const firstClass=JSON.parse(run('JSON.stringify(getRoster())'));const firstClassKey='class:'+firstClass.id;
ctx.otherFile={name:'different.xlsx'};element('rosterName').value='  الصف الاول - أ  ';
const unchanged=storage.get('lughaty-oral-diagnostic.roster');
assert.throws(()=>run('saveImportedRoster(otherFile,classStudents)'),/مستخدم مسبقًا/);
assert.equal(storage.get('lughaty-oral-diagnostic.roster'),unchanged);
element('rosterFile').value='different.xlsx';await run('importRoster(otherFile)');assert.equal(element('rosterFile').value,'');assert.ok(element('rosterMessage').textContent.includes('مستخدم مسبقًا'));assert.equal(storage.get('lughaty-oral-diagnostic.roster'),unchanged);
run('saveImportedRoster(classFile,classStudents)');assert.equal(run('getRosterStore().rosters.length'),1);assert.equal(run('getRoster().id'),firstClass.id);
assert.notEqual(run("classNameKey('1 أ')"),run("classNameKey('2 أ')"));
assert.equal(run("classNameKey('الصَّفُّ الأوَّل — أ')"),run("classNameKey('الصف الاول - أ')"));
assert.ok(!ids.includes('errorType')&&!ids.includes('errorTypeWrap'));
element('level').value='one';element('wordSession').value='full';run('updateRosterMessage()');element('start').click();
const firstSession=run('currentTestSession.id');assert.equal(run('assessmentStartedAt'),0);run("mark('✓')");
assert.equal(JSON.parse(storage.get('lughaty-oral-diagnostic.draft')).testSession.id,firstSession);
run('goHome();currentTestSession=null;resumeDraft()');assert.equal(run('currentTestSession.id'),firstSession);
now+=61000;run('completeAssessment()');assert.equal(run('activeRecord.testSessionId'),firstSession);assert.equal(run('activeRecord.durationSeconds'),61);
element('nextStudent').click();assert.equal(run('currentTestSession.id'),firstSession);assert.equal(run('assessmentStartedAt'),0);run("mark('✕');completeAssessment()");
assert.equal(run('activeRecord.items[0].errorType'),'');
element('nextStudent').click();run('skipAbsentStudent()');assert.equal(run('getTestSessions()[currentTestSession.id].absentStudentIds[getRoster().students[2].id]'),true);
run('goHome();const rr=getRoster();rr.currentIndex=0;saveRoster(rr);updateRosterMessage()');element('start').click();
const secondSession=run('currentTestSession.id');assert.notEqual(secondSession,firstSession);run("mark('✕');completeAssessment()");
ctx.classFile={name:'second.xlsx'};ctx.classStudents=[{name:'خالد الغامدي'}];element('rosterName').value='الصف الثاني — أ';run('saveImportedRoster(classFile,classStudents)');const secondClass=JSON.parse(run('JSON.stringify(getRoster())'));
const recordBytes=storage.get('lughaty-oral-diagnostic.records');
element('navHistory').click();assert.equal(run('historyClassKey'),null);assert.ok(element('historyList').innerHTML.includes('الصف الثاني'));
const classButtons=document.querySelectorAll('[data-history-class]');assert.equal(classButtons.length,2);classButtons.find(b=>b.dataset.historyClass===firstClassKey).click();
assert.equal(run('historyClassKey'),firstClassKey);assert.equal(run('historyTests(historyScope().group).length'),2);
assert.equal(run('historyScope().group.records.length'),3);
const testButtons=document.querySelectorAll('[data-history-test]');assert.equal(testButtons.length,2);testButtons.find(b=>b.dataset.historyTest===firstSession).click();
assert.ok(element('historyList').innerHTML.includes('ريم الحربي'));assert.ok(element('historyList').innerHTML.includes('عمر العتيبي'));assert.equal(run('historyScope().records.length'),2);
assert.equal(run('historyReportRoster().id'),firstClass.id);assert.equal(run('getRoster().id'),secondClass.id);
assert.equal(run('classRows()[0][2]'),'100%');assert.equal(run('classRows()[2][1]'),'غائب');
run('renderAllReport()');assert.ok(!element('allReportContent').innerHTML.includes('خالد الغامدي'));assert.ok(element('allReportContent').innerHTML.includes('اختبار'));
assert.equal(storage.get('lughaty-oral-diagnostic.records'),recordBytes);
element('closeAllReport').click();assert.equal(run('historyTestKey'),firstSession);
element('historyClassParent').click();assert.equal(run('historyTestKey'),null);assert.equal(run('historyClassKey'),firstClassKey);
element('historyRoot').click();assert.equal(run('historyClassKey'),null);
element('historySearch').value='الثاني';element('historySearch').dispatchEvent(new Event('input'));assert.equal(document.querySelectorAll('[data-history-class]').length,1);
// Same-day sessions stay separate. Legacy results get date/level folders without rewriting them.
ctx.legacyRows=[{...record,id:'legacy-a',studentName:'ريم الحربي',studentId:firstClass.students[0].id,rosterId:firstClass.id,rosterName:firstClass.name,testSessionId:null,testSessionStartedAt:null,completedAt:'2026-10-04T20:50:00Z',level:'one',plannedTotal:28},{...record,id:'legacy-b',studentName:'عمر العتيبي',studentId:firstClass.students[1].id,rosterId:firstClass.id,rosterName:firstClass.name,testSessionId:null,testSessionStartedAt:null,completedAt:'2026-10-04T21:10:00Z',level:'one',plannedTotal:28}];
run('const oldStore=getStore();oldStore.records.push(...legacyRows);saveStore(oldStore)');const legacyBytes=storage.get('lughaty-oral-diagnostic.records');ctx.firstClassKey=firstClassKey;
run('openHistoryClass(firstClassKey)');assert.equal(run('historyTests(historyScope().group).length'),4);
assert.equal(run('historyTests(historyScope().group).filter(test=>test.legacy).length'),2);assert.notEqual(run('historyTestFor(legacyRows[0])'),run('historyTestFor(legacyRows[1])'));
assert.equal(storage.get('lughaty-oral-diagnostic.records'),legacyBytes);assert.ok(element('historyList').innerHTML.includes('أرشيف النسخة السابقة'));
const legacyButtons=document.querySelectorAll('[data-history-test]');legacyButtons.find(b=>b.dataset.historyTest.startsWith('legacy:')).click();assert.equal(run('historyScope().records.length'),1);
element('historyShowAll').click();assert.equal(run('historyAll'),true);assert.equal(run('historyScope().records.length'),5);
console.log('PASS: class/test folder clicks, unique dated batches, next-student and resume continuity, session absence, duplicate class prevention, legacy date folders, folder-scoped reports without record mutation');
console.log('PASS: offline DOCX/XLSX roster extraction with guardian association');})().catch(e=>{console.error(e);process.exitCode=1});
